[workspace]

resolver = "2"
members = [
	"chapter-1/hello-cargo",
	"chapter-2/guessing-game",
	"chapter-3/control-flow",
	"chapter-3/data-types",
	"chapter-3/functions",
	"chapter-3/variables",
	"chapter-5/structs",
	"chapter-6/enums",
	"chapter-6/if-let",
	"chapter-6/match-learning",
	"chapter-8/hash-maps",
	"chapter-8/strings",
	"chapter-8/vectors",
	"chapter-9/errors",
	"chapter-10/generics",
	"chapter-10/largest",
	"chapter-10/traits",
	"chapter-10/validating-references-with-lifetimes",
	"chapter-11/adder",
	"chapter-11/test-modules",
	"chapter-12/minigrep",
	"chapter-13/closures",
	"chapter-13/iterators",
	"chapter-14/crates",
	"chapter-15/box-pointer",
	"chapter-15/custom-pointers",
	"chapter-15/data-tree",
	"chapter-15/refcell",
	"chapter-15/reference-counting"
]
